#!/usr/bin/env node
// Renders each figure's rest pose to a static SVG (the no-JS drawing) and writes
// the kernel's own CSS as a static stylesheet, so snapshots are styled without JS.
// `node scripts/hairline/snapshot.mjs` writes; `--check` fails if anything would change.
import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { chromium } from "@playwright/test";
import { assemble } from "../../hairline/kit/build.mjs";

const root = (p) => fileURLToPath(new URL(`../../${p}`, import.meta.url));
const check = process.argv.includes("--check");
const names = readdirSync(root("hairline/figures"))
  .filter((f) => f.endsWith(".js"))
  .map((f) => f.slice(0, -3));
const kernel = readFileSync(root("hairline/kit/kernel.js"), "utf8");
const browser = await chromium.launch();
const page = await browser.newPage({
  viewport: { width: 800, height: 900 },
  reducedMotion: "reduce",
});
const out = new Map();
let css = "";

for (const name of names) {
  const figure = readFileSync(root(`hairline/figures/${name}.js`), "utf8");
  await page.setContent(assemble(figure), { waitUntil: "load" });
  await page.waitForFunction(
    () => document.querySelector("#stage > svg")?.childElementCount > 0,
  );
  // Staggered tweens can still be landing on a slow machine: capture only once
  // the drawing has stayed the same for half a second.
  await page.waitForFunction(
    () => {
      const now = document.querySelector("#stage > svg").outerHTML;
      const w = /** @type {any} */ (window);
      if (now !== w.__last) [w.__last, w.__since] = [now, performance.now()];
      return performance.now() - w.__since >= 500;
    },
    null,
    { polling: 100 },
  );
  const svg = await page.evaluate(() => {
    const s = document.querySelector("#stage > svg").cloneNode(true);
    s.removeAttribute("style");
    return s.outerHTML;
  });
  if (!css) css = await page.evaluate(() => window.HL.css(true));
  // Ids are prefixed per figure, so several snapshots can share one page.
  const scoped = svg
    .replace(/id="([^"]+)"/g, `id="${name}-$1"`)
    .replace(/url\(#([^)]+)\)/g, `url(#${name}-$1)`);
  const hash = createHash("sha256")
    .update(kernel)
    .update(figure)
    .digest("hex")
    .slice(0, 12);
  out.set(
    `src/hairline/snapshots/${name}.svg`,
    `<!-- ${name} rest pose, from figure+kernel ${hash} -->\n${scoped}\n`,
  );
}
await browser.close();
out.set(
  "src/styles/hairline.css",
  `/* Generated by scripts/hairline/snapshot.mjs from HL.css(true). Do not edit. */\n${css}\n`,
);

let stale = 0;
for (const [file, text] of out) {
  const now = existsSync(root(file)) ? readFileSync(root(file), "utf8") : "";
  if (now === text) continue;
  stale++;
  if (check) console.error(`stale: ${file} (run npm run figures)`);
  else writeFileSync(root(file), text);
}
console.log(
  check
    ? stale
      ? `${stale} stale`
      : "figures up to date"
    : `wrote ${out.size} files`,
);
process.exit(check && stale ? 1 : 0);
